package coding.creditmanagement.mapper;

import coding.creditmanagement.entity.CardCredit;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CardCreditMapper {

    CardCredit selectForUpdate(String cardId);

    String selectRandomCardId();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_credit
     *
     * @mbg.generated Mon Sep 02 01:54:22 CST 2024
     */
    int deleteByPrimaryKey(String cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_credit
     *
     * @mbg.generated Mon Sep 02 01:54:22 CST 2024
     */
    int insert(CardCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_credit
     *
     * @mbg.generated Mon Sep 02 01:54:22 CST 2024
     */
    int insertSelective(CardCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_credit
     *
     * @mbg.generated Mon Sep 02 01:54:22 CST 2024
     */
    CardCredit selectByPrimaryKey(String cardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_credit
     *
     * @mbg.generated Mon Sep 02 01:54:22 CST 2024
     */
    int updateByPrimaryKeySelective(CardCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_credit
     *
     * @mbg.generated Mon Sep 02 01:54:22 CST 2024
     */
    int updateByPrimaryKey(CardCredit record);
}